---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: ssh://git@github.com/alecrubindev/watchtower
    ref: master
    path: charts/podinfo-v1
  values:
    image:
      repository: alecrubin/podinfo
      tag: dev-syprhxnw
    replicaCount: 1
