repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: kuber-charts
    url: https://kuber-charts.storage.googleapis.com
  - name: weaveworks
    url: https://weaveworks.github.io/flux

context: gke_kuber-221407_us-central1-c_watchtower

helmDefaults:
  kubeContext: gke_kuber-221407_us-central1-c_watchtower
  recreatePods: true
  force: true

releases:
  - name: flux
    namespace: flux
    chart: weaveworks/flux
    values:
      - git:
          url: git@github.com:alecrubindev/watchtower
        helmOperator:
          create: true
          git:
            chartsPath: charts
